# Generated by Django 6.0.1 on 2026-01-23 02:56

import django.core.validators
import django.db.models.deletion
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип документа')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'equipment_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='5-значный код объекта, например: 22256', max_length=5, unique=True, validators=[main.models.validate_location_code], verbose_name='Код объекта')),
                ('address', models.CharField(help_text='Полный адрес места нахождения, например: г. Краснодар, ул. Ленина, 1', max_length=255, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Место нахождения',
                'verbose_name_plural': 'Места нахождения',
                'db_table': 'location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Производитель')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Например: ООО "Ромашка"', max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(help_text='ИНН организации (10 цифр)', max_length=10, unique=True, validators=[main.models.validate_organization_inn], verbose_name='ИНН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('is_head', models.BooleanField(default=True, help_text='Отметьте, если это головная организация', verbose_name='Головная организация')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название подразделения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', related_query_name='dept', to='main.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название должности')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'position',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('kabinet', models.CharField(blank=True, default='', max_length=4, verbose_name='Кабинет')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.employee_photo_upload_path, validators=[main.models.validate_image_file], verbose_name='Фото')),
                ('login', models.CharField(max_length=11, unique=True, validators=[main.models.validate_login], verbose_name='Логин')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='emp', to='main.department', verbose_name='Подразделение')),
                ('location', models.ForeignKey(help_text='Код и адрес объекта, где работает сотрудник', on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='loc_emp', to='main.location', verbose_name='Место нахождения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='position_emp', to='main.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Поддерживаются: PDF, DOC/X, XLS/X, изображения, архивы (до 10 МБ)', upload_to=main.models.generate_employee_document_path, validators=[main.models.validate_document_file], verbose_name='Файл документа')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о документе', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть документ (не удаляя файл)', verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='main.documenttype', verbose_name='Тип документа')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='main.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'document',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['employee', '-created'], name='document_employe_bdba94_idx'), models.Index(fields=['type'], name='document_type_id_1eb823_idx')],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('serial_number', models.CharField(help_text='Уникальный серийный номер', max_length=100, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, help_text='Номер в бухгалтерии', max_length=50, null=True, unique=True, verbose_name='Инвентарный номер')),
                ('year_of_release', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('status', models.CharField(choices=[('storage', 'На складе'), ('awaiting', 'Ожидает постановки на баланс'), ('write_off', 'На списании'), ('written_off', 'Списано'), ('temporary', 'Выдано во временное пользование'), ('assigned', 'Закреплено за сотрудником')], default='storage', max_length=20, verbose_name='Статус')),
                ('network_name', models.CharField(blank=True, help_text='Имя в сети (например, PC-001)', max_length=100, null=True, unique=True, verbose_name='Сетевое имя')),
                ('photo', models.ImageField(blank=True, help_text='Фото оборудования (до 5 МБ, форматы: JPG, PNG, WebP)', null=True, upload_to=main.models.equipment_photo_upload_path, validators=[main.models.validate_equipment_image], verbose_name='Фотография')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='main.employee', verbose_name='Ответственный')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='main.equipmenttype', verbose_name='Тип оборудования')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='main.location', verbose_name='Место нахождения')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='main.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('responsible__isnull', False), ('status', 'assigned')), models.Q(('status', 'assigned'), _negated=True), _connector='OR'), name='assigned_requires_responsible'), models.CheckConstraint(condition=models.Q(models.Q(('responsible__isnull', False), ('status', 'temporary')), models.Q(('status', 'temporary'), _negated=True), _connector='OR'), name='temporary_requires_responsible')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Дата вступления в должность / перевода', verbose_name='Начало периода')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте пустым, если сотрудник работает по настоящее время', null=True, verbose_name='Окончание периода')),
                ('reason', models.CharField(blank=True, help_text='Например: повышение, перевод, реорганизация, совмещение', max_length=255, verbose_name='Причина изменения')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если это актуальное назначение сотрудника', verbose_name='Текущая запись')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='main.employee', verbose_name='Сотрудник')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='Место нахождения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Запись истории сотрудника',
                'verbose_name_plural': 'История сотрудников',
                'db_table': 'employee_history',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lt', models.F('end_date')), _connector='OR'), name='check_end_date_after_start_date')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['last_name', 'first_name'], name='employee_last_na_acd780_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['login'], name='employee_login_ba9b95_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['available', 'department'], name='employee_availab_3b920e_idx'),
        ),
    ]
