# Generated by Django 6.0.1 on 2026-01-15 18:46

import django.db.models.deletion
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='5-значный код объекта, например: 22256', max_length=5, unique=True, validators=[main.models.validate_location_code], verbose_name='Код объекта')),
                ('address', models.CharField(help_text='Полный адрес места нахождения, например: г. Краснодар, ул. Ленина, 1', max_length=255, verbose_name='Адрес')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Место нахождения',
                'verbose_name_plural': 'Места нахождения',
                'db_table': 'location',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Например: ООО "Ромашка"', max_length=255, verbose_name='Название организации')),
                ('inn', models.CharField(help_text='ИНН организации (10 цифр)', max_length=10, unique=True, validators=[main.models.validate_organization_inn], verbose_name='ИНН')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('is_head', models.BooleanField(default=True, help_text='Отметьте, если это головная организация', verbose_name='Головная организация')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'db_table': 'organization',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название подразделения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', related_query_name='dept', to='main.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название должности')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'position',
                'ordering': ['name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_employee_image_path, validators=[main.models.validate_image_file])),
                ('login', models.CharField(max_length=11, unique=True, validators=[main.models.validate_login], verbose_name='Логин')),
                ('available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='emp', to='main.department', verbose_name='Подразделение')),
                ('location', models.ForeignKey(help_text='Код и адрес объекта, где работает сотрудник', on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='loc_emp', to='main.location', verbose_name='Место нахождения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', related_query_name='position_emp', to='main.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'ordering': ['-created'],
            },
        ),
    ]
