# Generated by Django 6.0.1 on 2026-01-16 07:13

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kabinet',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_employee_image_path, validators=[main.models.validate_image_file], verbose_name='Фото'),
        ),
    ]
