# Generated by Django 6.0.1 on 2026-01-23 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinuxCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('icon', models.CharField(blank=True, help_text='Название иконки FontAwesome (например: fa-folder, fa-terminal)', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Категория Linux',
                'verbose_name_plural': 'Категории Linux',
                'db_table': 'linux_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LinuxCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('command', models.CharField(max_length=200, verbose_name='Команда')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('usage', models.TextField(help_text='Пример использования команды', verbose_name='Использование')),
                ('options', models.TextField(blank=True, help_text='Основные опции команды (каждая с новой строки)', verbose_name='Опции/ключи')),
                ('examples', models.TextField(blank=True, help_text='Примеры использования (каждый с новой строки)', verbose_name='Примеры')),
                ('difficulty', models.CharField(choices=[('beginner', 'Новичок'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Сложность')),
                ('tags', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=255, verbose_name='Теги')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='main.linuxcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Linux команда',
                'verbose_name_plural': 'Linux команды',
                'db_table': 'linux_command',
                'ordering': ['order', 'command'],
                'unique_together': {('command', 'category')},
            },
        ),
        migrations.CreateModel(
            name='LinuxCheatsheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название шпаргалки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Содержимое (Markdown)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Скачиваний')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='main.linuxcategory', verbose_name='Категории')),
                ('commands', models.ManyToManyField(blank=True, to='main.linuxcommand', verbose_name='Команды')),
            ],
            options={
                'verbose_name': 'Шпаргалка Linux',
                'verbose_name_plural': 'Шпаргалки Linux',
                'db_table': 'linux_cheatsheet',
                'ordering': ['-created'],
            },
        ),
    ]
