# Generated by Django 6.0.1 on 2026-01-19 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_kabinet_employee_phone_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Дата вступления в должность / перевода', verbose_name='Начало периода')),
                ('end_date', models.DateField(blank=True, help_text='Оставьте пустым, если сотрудник работает по настоящее время', null=True, verbose_name='Окончание периода')),
                ('reason', models.CharField(blank=True, help_text='Например: повышение, перевод, реорганизация, совмещение', max_length=255, verbose_name='Причина изменения')),
                ('is_active', models.BooleanField(default=True, help_text='Отметьте, если это актуальное назначение сотрудника', verbose_name='Текущая запись')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='Подразделение')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='main.employee', verbose_name='Сотрудник')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.location', verbose_name='Место нахождения')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Запись истории сотрудника',
                'verbose_name_plural': 'История сотрудников',
                'db_table': 'employee_history',
                'ordering': ['-start_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('start_date__lt', models.F('end_date')), _connector='OR'), name='check_end_date_after_start_date')],
            },
        ),
    ]
