# Generated by Django 6.0.1 on 2026-01-25 04:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_linuxcategory_linuxcommand_linuxcheatsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='linuxcheatsheet',
            name='file_html',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='cheatsheets/'), upload_to='cheatsheets/html/', verbose_name='HTML файл'),
        ),
        migrations.AddField(
            model_name='linuxcheatsheet',
            name='file_md',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='cheatsheets/'), upload_to='cheatsheets/md/', verbose_name='Markdown файл'),
        ),
        migrations.AddField(
            model_name='linuxcheatsheet',
            name='file_pdf',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='cheatsheets/'), upload_to='cheatsheets/pdf/', verbose_name='PDF файл'),
        ),
        migrations.AddField(
            model_name='linuxcheatsheet',
            name='file_txt',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='cheatsheets/'), upload_to='cheatsheets/txt/', verbose_name='Text файл'),
        ),
    ]
