# Generated by Django 6.0.1 on 2026-01-19 13:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_employeehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
                'db_table': 'equipment_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Производитель')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'db_table': 'manufacturer',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=150, verbose_name='Модель')),
                ('serial_number', models.CharField(help_text='Уникальный серийный номер', max_length=100, unique=True, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, help_text='Номер в бухгалтерии', max_length=50, null=True, unique=True, verbose_name='Инвентарный номер')),
                ('year_of_release', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2030)], verbose_name='Год выпуска')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('status', models.CharField(choices=[('storage', 'На складе'), ('awaiting', 'Ожидает постановки на баланс'), ('write_off', 'На списании'), ('written_off', 'Списано'), ('temporary', 'Выдано во временное пользование'), ('assigned', 'Закреплено за сотрудником')], default='storage', max_length=20, verbose_name='Статус')),
                ('network_name', models.CharField(blank=True, help_text='Имя в сети (например, PC-001)', max_length=100, null=True, unique=True, verbose_name='Сетевое имя')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='main.location', verbose_name='Место нахождения')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment', to='main.employee', verbose_name='Ответственный')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='main.equipmenttype', verbose_name='Тип оборудования')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='main.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'db_table': 'equipment',
                'ordering': ['-created'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('responsible__isnull', False), ('status', 'assigned')), models.Q(('status', 'assigned'), _negated=True), _connector='OR'), name='assigned_requires_responsible'), models.CheckConstraint(condition=models.Q(models.Q(('responsible__isnull', False), ('status', 'temporary')), models.Q(('status', 'temporary'), _negated=True), _connector='OR'), name='temporary_requires_responsible')],
            },
        ),
    ]
