# Generated by Django 6.0.1 on 2026-01-20 12:58

import django.db.models.deletion
import main.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_equipmenttype_manufacturer_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип документа')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
                'db_table': 'document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название документа')),
                ('file', models.FileField(help_text='Поддерживаются: PDF, DOC/X, XLS/X, изображения, архивы (до 10 МБ)', upload_to=main.models.get_employee_document_path, validators=[main.models.validate_document_file], verbose_name='Файл документа')),
                ('description', models.TextField(blank=True, help_text='Дополнительная информация о документе', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть документ (не удаляя файл)', verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='main.employee', verbose_name='Сотрудник')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='main.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': 'document',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['employee', '-created'], name='document_employe_bdba94_idx'), models.Index(fields=['type'], name='document_type_id_1eb823_idx')],
            },
        ),
    ]
