# Generated by Django 6.0.1 on 2026-01-22 04:31

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_documenttype_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото оборудования (до 5 МБ, форматы: JPG, PNG, WebP)', null=True, upload_to='equipment/photos/%Y/%m/%d/', validators=[main.models.validate_equipment_image], verbose_name='Фотография'),
        ),
    ]
